ZHIPU:
  API_KEY: "11e78cf9b1cb4b58bc7f18a9dbd0c299.KX46JNWt9iYXuwHz"

  
APP:
  DEBUG: true
  LOG_LEVEL: "INFO"

MYSQL:
  HOST: "localhost"
  PORT: 3306
  USER: "root"
  PASSWORD: "root"
  DB: "resume_db"